SUMX(FILTER(FILTER(FILTER('Park Visits', 'Park Visits'[Park Unit] = 'Park Data'[Park Unit]), YEAR('Park Visits'[Date]) = 'Park Data'[First Year as Park]), 'Park Data'[Included in Analysis] = TRUE), 'Park Visits'[Visits])