let
    Source = Web.BrowserContents("https://en.wikipedia.org/wiki/List_of_national_parks_of_the_United_States"),
    #"Extracted Table From Html" = Html.Table(Source, {{"Column1", "TABLE.wikitable.sortable.plainrowheaders > * > TR > :nth-child(1)"}, {"Column2", "TABLE.wikitable.sortable.plainrowheaders > * > TR > :nth-child(2)"}, {"Column3", "TABLE.wikitable.sortable.plainrowheaders > * > TR > :nth-child(3)"}, {"Column4", "TABLE.wikitable.sortable.plainrowheaders > * > TR > :nth-child(4)"}, {"Column5", "TABLE.wikitable.sortable.plainrowheaders > * > TR > :nth-child(5)"}, {"Column6", "TABLE.wikitable.sortable.plainrowheaders > * > TR > :nth-child(6)"}, {"Column7", "TABLE.wikitable.sortable.plainrowheaders > * > TR > :nth-child(7)"}}, [RowSelector="TABLE.wikitable.sortable.plainrowheaders > * > TR"]),
    #"Promoted Headers" = Table.PromoteHeaders(#"Extracted Table From Html", [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Name", type text}, {"Image", type text}, {"Location", type text}, {"Date established as park[7][12]", type text}, {"Area (2021)[13]", type text}, {"Recreation visitors (2021)[11]", Int64.Type}, {"Description", type text}}),
    #"Merged Queries" = Table.FuzzyNestedJoin(#"Changed Type", {"Name"}, #"Park Media", {"Name"}, "Park Media", JoinKind.LeftOuter, [IgnoreCase=true, IgnoreSpace=true]),
    #"Expanded Park Media" = Table.ExpandTableColumn(#"Merged Queries", "Park Media", {"Image Link"}, {"Image Link"}),
    #"Merged Queries1" = Table.FuzzyNestedJoin(#"Expanded Park Media", {"Name"}, #"Park Units", {"Park Name"}, "Park Units", JoinKind.LeftOuter, [IgnoreCase=true, IgnoreSpace=true]),
    #"Expanded Park Units" = Table.ExpandTableColumn(#"Merged Queries1", "Park Units", {"Park Unit", "Park Name"}, {"Park Unit", "Park Name"}),
    #"Reordered Columns" = Table.ReorderColumns(#"Expanded Park Units",{"Park Unit", "Park Name", "Name", "Image", "Location", "Date established as park[7][12]", "Area (2021)[13]", "Recreation visitors (2021)[11]", "Description", "Image Link"}),
    #"Removed Columns" = Table.RemoveColumns(#"Reordered Columns",{"Name", "Image"}),
    #"Split Column by Delimiter" = Table.SplitColumn(#"Removed Columns", "Date established as park[7][12]", Splitter.SplitTextByEachDelimiter({"["}, QuoteStyle.Csv, false), {"Date established as park[7][12].1", "Date established as park[7][12].2"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Date established as park[7][12].1", type text}, {"Date established as park[7][12].2", type text}}),
    #"Removed Columns1" = Table.RemoveColumns(#"Changed Type1",{"Date established as park[7][12].2"}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Removed Columns1",{{"Date established as park[7][12].1", type date}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type2",{{"Date established as park[7][12].1", "Date Established"}}),
    #"Split Column by Delimiter1" = Table.SplitColumn(#"Renamed Columns", "Area (2021)[13]", Splitter.SplitTextByEachDelimiter({" "}, QuoteStyle.Csv, false), {"Area (2021)[13].1", "Area (2021)[13].2"}),
    #"Changed Type3" = Table.TransformColumnTypes(#"Split Column by Delimiter1",{{"Area (2021)[13].1", type number}, {"Area (2021)[13].2", type text}}),
    #"Removed Columns2" = Table.RemoveColumns(#"Changed Type3",{"Area (2021)[13].2"}),
    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns2",{{"Area (2021)[13].1", "Area in Acres"}}),
    #"Removed Columns3" = Table.RemoveColumns(#"Renamed Columns1",{"Recreation visitors (2021)[11]"}),
    #"Added Custom" = Table.AddColumn(#"Removed Columns3", "State", each Text.Start([Location], Text.PositionOfAny([Location], {"0".."9"}))),
    #"Reordered Columns1" = Table.ReorderColumns(#"Added Custom",{"Park Unit", "Park Name", "State", "Location", "Date Established", "Area in Acres", "Description", "Image Link"}),
    #"Split Column by Delimiter2" = Table.SplitColumn(#"Reordered Columns1", "Location", Splitter.SplitTextByEachDelimiter({"/"}, QuoteStyle.Csv, true), {"Location.1", "Location.2"}),
    #"Changed Type4" = Table.TransformColumnTypes(#"Split Column by Delimiter2",{{"Location.1", type text}, {"Location.2", type text}}),
    #"Split Column by Delimiter3" = Table.SplitColumn(#"Changed Type4", "Location.2", Splitter.SplitTextByEachDelimiter({";"}, QuoteStyle.Csv, false), {"Location.2.1", "Location.2.2"}),
    #"Split Column by Delimiter4" = Table.SplitColumn(#"Split Column by Delimiter3", "Location.2.2", Splitter.SplitTextByEachDelimiter({"﻿ ("}, QuoteStyle.Csv, false), {"Location.2.2.1", "Location.2.2.2"}),
    #"Replaced Value" = Table.ReplaceValue(#"Split Column by Delimiter4",")","",Replacer.ReplaceText,{"Location.2.2.2"}),
    #"Removed Columns4" = Table.RemoveColumns(#"Replaced Value",{"Location.1"}),
    #"Renamed Columns2" = Table.RenameColumns(#"Removed Columns4",{{"Location.2.1", "Latitude"}, {"Location.2.2.1", "Longitude"}, {"Location.2.2.2", "Alternate Name"}}),
    #"Split Column by Delimiter5" = Table.SplitColumn(#"Renamed Columns2", "State", Splitter.SplitTextByEachDelimiter({","}, QuoteStyle.Csv, false), {"State", "Extra States"}),
    #"Removed Columns5" = Table.RemoveColumns(#"Split Column by Delimiter5",{"Extra States"}),
    #"Changed Type5" = Table.TransformColumnTypes(#"Removed Columns5",{{"Latitude", type number}, {"Longitude", type number}}),
    #"Added Custom1" = Table.AddColumn(#"Changed Type5", "Temp.1", each List.RemoveMatchingItems(Text.Split([Description],"]"),{""})),
    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "Temp.2", each List.Transform([Temp.1], each Text.Start(_ , Text.PositionOf(_ , "[")))),
    #"Added Custom3" = Table.AddColumn(#"Added Custom2", "Final Description", each Text.Combine([Temp.2])),
    #"Replaced Value1" = Table.ReplaceValue(#"Added Custom3","(BR)","",Replacer.ReplaceText,{"Final Description"}),
    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","(WHS)","",Replacer.ReplaceText,{"Final Description"}),
    #"Removed Columns6" = Table.RemoveColumns(#"Replaced Value2",{"Description", "Temp.1", "Temp.2"}),
    #"Renamed Columns3" = Table.RenameColumns(#"Removed Columns6",{{"Final Description", "Description"}}),
    #"Reordered Columns2" = Table.ReorderColumns(#"Renamed Columns3",{"Park Unit", "Park Name", "State", "Latitude", "Longitude", "Alternate Name", "Date Established", "Area in Acres", "Description", "Image Link"})
in
    #"Reordered Columns2"